export const APP_NAME = process.env.NEXT_PUBLIC_APP_NAME ?? "PetroTrade Seller";

export const APP_URL =
  process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000";

export const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL ?? "";

export const IS_DEV = process.env.NODE_ENV === "development";

export const IS_PROD = process.env.NODE_ENV === "production";

export const DEFAULT_PAGE_SIZE = 10;

export const MAX_PAGE_SIZE = 100;

export const DEBOUNCE_MS = 300;

export const STORAGE_KEYS = {
  AUTH_TOKEN: "petrotrade_auth_token",
  REFRESH_TOKEN: "petrotrade_refresh_token",
  USER_PREFERENCES: "petrotrade_user_preferences",
  THEME: "petrotrade_theme",
  ONBOARDING: "petrotrade-onboarding",
  CX_PUBLISHED: "petrotrade_cx_published",
  AUTH_SESSION: "petrotrade_seller_session",
  SELECTED_LOCATION: "petrotrade_selected_location_v2",
} as const;

export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  VERIFY_OTP: "/verify-otp",
  OTP: "/otp",
  SELLER_LOGIN: "/login",
  SELLER_OTP: "/otp",
  ONBOARDING: "/onboarding",
  ONBOARDING_COMPANY: "/onboarding/company",
  ONBOARDING_BUSINESS: "/onboarding/business",
  ONBOARDING_DOCUMENTS: "/onboarding/documents",
  ONBOARDING_GST: "/onboarding/gst",
  ONBOARDING_GST_PAN: "/onboarding/gst",
  ONBOARDING_BANK: "/onboarding/bank",
  ONBOARDING_LOCATION: "/onboarding/location",
  ONBOARDING_LOCATIONS: "/onboarding/locations",
  ONBOARDING_REVIEW: "/onboarding/review",
  ONBOARDING_SUBMITTED: "/onboarding/review",
  DASHBOARD: "/dashboard",
  PRODUCTS: "/products",
  PRODUCTS_NEW: "/products/new",
  INVENTORY: "/products",
  INVENTORY_ADD_PRODUCT: "/products/new",
  OFFERS: "/offers",
  OFFERS_NEW: "/offers/new",
  OFFERS_CREATE: "/offers/new",
  OFFERS_EDIT: "/offers",
  OFFERS_PREVIEW: "/offers",
  PURCHASE_REQUESTS: "/purchase-requests",
  ORDERS: "/orders",
  ORDER_MANAGEMENT: "/orders",
  ORDER_DETAIL: "/orders",
  DISPATCH: "/dispatch",
  VEHICLE_SLOT_BOOKING: "/dispatch",
  SHIPMENTS: "/shipments",
  SHIPMENT_TRACKING: "/shipments",
  SETTLEMENTS: "/settlements",
  PAYMENTS: "/payments",
  RECEIVABLES: "/settlements",
  CREDIT_INSURANCE: "/settlements",
  DOCUMENTS: "/documents",
  DOCUMENT_CENTER: "/documents",
  PROFILE: "/profile",
  PROFILE_COMPANY: "/profile/company",
  PROFILE_LOCATIONS: "/profile/locations",
  PROFILE_BANK: "/profile/bank",
  PROFILE_ACCOUNT_MANAGER: "/profile/account-manager",
  NOTIFICATIONS: "/notifications",
  SUPPORT: "/support",
  SETTINGS: "/settings",
  SEARCH: "/search",
  LOGOUT: "/login",
  KYC: "/dashboard",
  PRICE_REVISIONS: "/offers",
  OFFER_REVIEW: "/offers",
  OFFER_REVIEW_STATUS: "/offers",
  ANALYTICS: "/dashboard",
  REPORTS: "/dashboard",
  PERFORMANCE_DASHBOARD: "/dashboard",
  CUSTOMERS: "/dashboard",
  CUSTOMER_DETAIL: "/dashboard",
  CUSTOMER_REQUESTS: "/purchase-requests",
  CUSTOMER_ORDERS: "/orders",
  CUSTOMER_SUPPORT: "/support",
  CUSTOMER_NOTIFICATIONS: "/notifications",
  MARKETPLACE_CATALOG: "/products",
  MARKETPLACE_CATEGORIES: "/products",
  MARKETPLACE_PRICING: "/offers",
  MARKETPLACE_OFFERS: "/offers",
  CMS_HOME: "/dashboard",
  CMS_BANNERS: "/dashboard",
  CMS_MEDIA: "/dashboard",
  CMS_VIDEOS: "/dashboard",
  CMS_PROMOTIONS: "/dashboard",
  AUDIT_LOGS: "/dashboard",
  PROCUREMENT: "/purchase-requests",
  PROCUREMENT_QUEUE: "/purchase-requests",
  PROCUREMENT_ORDERS: "/orders",
  PROCUREMENT_SELLER_COMPARISON: "/dashboard",
  PROCUREMENT_NEGOTIATION: "/purchase-requests",
  PROCUREMENT_PURCHASE_REQUESTS: "/purchase-requests",
  PROCUREMENT_APPROVAL: "/purchase-requests",
  PROCUREMENT_REPORTS: "/dashboard",
  PROCUREMENT_TRACKING: "/shipments",
  PROCUREMENT_DOCUMENTS: "/documents",
  PROCUREMENT_SELLERS_NEW: "/dashboard",
} as const;

export const QUERY_KEYS = {
  DASHBOARD: "dashboard",
  INVENTORY: "inventory",
  PRODUCTS: "products",
  OFFERS: "offers",
  PURCHASE_REQUESTS: "purchase-requests",
  ORDERS: "orders",
  DISPATCH: "dispatch",
  SHIPMENTS: "shipments",
  ANALYTICS: "analytics",
  NOTIFICATIONS: "notifications",
  DOCUMENTS: "documents",
  PROFILE: "profile",
  SEARCH: "search",
  PROCUREMENT: "procurement",
  FINANCE: "finance",
  KYC: "kyc",
  CUSTOMERS: "customers",
  CATALOG: "catalog",
  CMS: "cms",
  SETTLEMENTS: "settlements",
} as const;
