import type {
  Notification,
  NotificationAttachment,
  NotificationCategory,
  NotificationPriority,
  NotificationTimelineEvent,
  RelatedOrder,
} from "@/types/notifications";

const PRODUCTS = [
  "LLDPE Film Grade",
  "HDPE Blow Moulding",
  "PP Raffia Grade",
  "PVC Resin K-67",
  "LDPE General Purpose",
  "PET Bottle Grade",
  "ABS Engineering Polymer",
  "Polycarbonate Sheet Grade",
];

const BUYERS = [
  "Reliance Poly Industries",
  "Bharat Plastics Ltd.",
  "Gujarat Polymer Corp.",
  "Maharashtra Resin Traders",
  "South India Packaging Co.",
  "Delhi Polymer Hub",
  "Chennai Chemical Works",
  "Kolkata Plastics Pvt. Ltd.",
];

function randomFrom<T>(items: T[]): T {
  return items[Math.floor(Math.random() * items.length)]!;
}

function padRef(num: number, prefix: string) {
  return `${prefix}-${String(num).padStart(4, "0")}`;
}

function buildTimeline(
  category: NotificationCategory,
  createdAt: string,
): NotificationTimelineEvent[] {
  const base = new Date(createdAt);
  const events: NotificationTimelineEvent[] = [
    {
      id: "1",
      title: "Notification Created",
      description: `${category} alert generated by PetroTrade ERP`,
      timestamp: createdAt,
      status: "completed",
    },
    {
      id: "2",
      title: "Seller Notified",
      description: "Alert delivered to ADMIN PANEL inbox",
      timestamp: new Date(base.getTime() - 2 * 60 * 1000).toISOString(),
      status: "completed",
    },
    {
      id: "3",
      title: "Awaiting Action",
      description: "Review and respond to this notification",
      timestamp: createdAt,
      status: "current",
    },
  ];
  return events;
}

function buildAttachments(
  category: NotificationCategory,
): NotificationAttachment[] {
  if (category === "Compliance Alert" || category === "Document Expiring") {
    return [
      {
        id: "att-1",
        name: "Compliance_Certificate.pdf",
        size: "245 KB",
        type: "PDF",
      },
      {
        id: "att-2",
        name: "Expiry_Notice.pdf",
        size: "128 KB",
        type: "PDF",
      },
    ];
  }
  if (
    category === "Purchase Request" ||
    category === "Settlement Released" ||
    category === "Dispatch Scheduled"
  ) {
    return [
      {
        id: "att-1",
        name: "Reference_Document.pdf",
        size: "312 KB",
        type: "PDF",
      },
    ];
  }
  return [];
}

function buildRelatedOrder(index: number): RelatedOrder | undefined {
  if (index % 3 !== 0) return undefined;
  return {
    id: `ord-${index}`,
    orderNumber: padRef(7700 + index, "ORD"),
    product: randomFrom(PRODUCTS),
    quantity: `${Math.floor(Math.random() * 40 + 10)} MT`,
    status: randomFrom(["Confirmed", "In Transit", "Processing", "Delivered"]),
  };
}

interface Template {
  category: NotificationCategory;
  priority: NotificationPriority;
  title: (ref: string) => string;
  description: (buyer: string, product: string) => string;
  referenceLabel?: string;
}

const TEMPLATES: Template[] = [
  {
    category: "Purchase Request",
    priority: "Urgent",
    title: (ref) => `Purchase Request Received ${ref}`,
    description: (buyer, product) =>
      `${buyer} has submitted a new purchase request for ${product}. Review pricing, availability, and delivery terms before accepting.`,
    referenceLabel: "Procurement ID",
  },
  {
    category: "Offer Approved",
    priority: "Medium",
    title: (ref) => `Offer Approved: ${ref}`,
    description: (_buyer, product) =>
      `Your offer for ${product} has been approved by the buyer. Proceed with order confirmation and slot booking.`,
  },
  {
    category: "Offer Changes Requested",
    priority: "High",
    title: () => "Offer Needs Changes: Price revision required",
    description: (buyer, product) =>
      `${buyer} has requested a price revision on your ${product} offer. Update the offer terms and resubmit for review.`,
  },
  {
    category: "Inventory Reserved",
    priority: "Low",
    title: (ref) => `Inventory Reserved against Order ${ref}`,
    description: (_buyer, product) =>
      `Stock for ${product} has been reserved in your warehouse. Dispatch scheduling will follow once payment is confirmed.`,
    referenceLabel: "Warehouse Ref",
  },
  {
    category: "Dispatch Scheduled",
    priority: "Medium",
    title: (ref) => `Dispatch Scheduled for Shipment ${ref}`,
    description: (_buyer, product) =>
      `Your ${product} shipment has been scheduled for pickup. Ensure all dispatch documents are ready for verification.`,
    referenceLabel: "Shipment Ref",
  },
  {
    category: "Shipment Delayed",
    priority: "High",
    title: (ref) => `Shipment Delayed ${ref}`,
    description: (_buyer, product) =>
      `The ${product} shipment has been delayed due to logistics constraints. Updated ETA will be shared shortly.`,
    referenceLabel: "Tracking Ref",
  },
  {
    category: "Settlement Released",
    priority: "Medium",
    title: (ref) => `Settlement Released for Invoice ${ref}`,
    description: (_buyer) =>
      "Payment settlement has been processed and released to your registered bank account. Check settlement dashboard for details.",
    referenceLabel: "Invoice Ref",
  },
  {
    category: "Compliance Alert",
    priority: "Critical",
    title: () => "Compliance Document Expiring",
    description: () =>
      "Your Pollution Control Board certificate is expiring within 7 days. Upload renewed documentation to avoid listing suspension.",
    referenceLabel: "Compliance Ref",
  },
  {
    category: "Document Expiring",
    priority: "Critical",
    title: () => "Regulatory Document Expiring Soon",
    description: () =>
      "One or more mandatory trade documents will expire soon. Renew and upload updated copies in the Compliance Center.",
    referenceLabel: "Document Ref",
  },
  {
    category: "System Update",
    priority: "Low",
    title: () => "System Update: New ADMIN PANEL Features",
    description: () =>
      "PetroTrade ADMIN PANEL has been updated with enhanced notification controls, export tools, and performance analytics.",
  },
];

const REF_PREFIXES: Record<NotificationCategory, string> = {
  "Purchase Request": "PR",
  "Offer Approved": "OFR",
  "Offer Changes Requested": "REV",
  "Inventory Reserved": "ORD",
  "Dispatch Scheduled": "SHP",
  "Shipment Delayed": "SHP",
  "Settlement Released": "INV",
  "Compliance Alert": "CMP",
  "Document Expiring": "DOC",
  "System Update": "SYS",
};

function generateNotifications(count: number): Notification[] {
  const notifications: Notification[] = [];
  const now = Date.now();

  for (let i = 0; i < count; i += 1) {
    const template = TEMPLATES[i % TEMPLATES.length]!;
    const product = PRODUCTS[i % PRODUCTS.length]!;
    const buyer = BUYERS[i % BUYERS.length]!;
    const prefix = REF_PREFIXES[template.category];
    const refNum = 8800 + count - i;
    const referenceNumber = padRef(refNum, prefix);

    const daysAgo = Math.floor(i / 3);
    const hoursAgo = (i * 37) % 24;
    const minutesAgo = (i * 13) % 60;
    const createdAt = new Date(
      now -
        daysAgo * 24 * 60 * 60 * 1000 -
        hoursAgo * 60 * 60 * 1000 -
        minutesAgo * 60 * 1000,
    ).toISOString();

    const title =
      template.category === "Offer Approved"
        ? `Offer Approved: ${product}`
        : template.title(
            template.category === "Offer Changes Requested"
              ? ""
              : `#${referenceNumber}`,
          );

    notifications.push({
      id: `notif-${String(i + 1).padStart(3, "0")}`,
      title,
      description: template.description(buyer, product),
      category: template.category,
      priority: template.priority,
      read: i > 28,
      archived: false,
      pinned: i < 2,
      referenceNumber,
      referenceLabel: template.referenceLabel
        ? `${template.referenceLabel} ${String(99 - (i % 30)).padStart(2, "0")}-${String(22 - (i % 10)).padStart(2, "0")}-A`
        : undefined,
      createdAt,
      timeline: buildTimeline(template.category, createdAt),
      attachments: buildAttachments(template.category),
      relatedOrder: buildRelatedOrder(i),
    });
  }

  return notifications.sort(
    (a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime(),
  );
}

export const notificationsMock = generateNotifications(80);

export const notificationsSummaryMock = {
  newPurchaseRequests: notificationsMock.filter(
    (n) => n.category === "Purchase Request" && !n.archived,
  ).length,
  priceRevisions: notificationsMock.filter(
    (n) => n.category === "Offer Changes Requested" && !n.archived,
  ).length,
  complianceAlerts: notificationsMock.filter(
    (n) =>
      (n.category === "Compliance Alert" ||
        n.category === "Document Expiring") &&
      !n.archived,
  ).length,
  dispatchUpdates: notificationsMock.filter(
    (n) =>
      (n.category === "Dispatch Scheduled" ||
        n.category === "Shipment Delayed") &&
      !n.archived,
  ).length,
  settlementUpdates: notificationsMock.filter(
    (n) => n.category === "Settlement Released" && !n.archived,
  ).length,
};
